const { PaymentMethodType, PaymentMethodTypeId } = require('../../../../dist/constants')
const { BCEnvironment, BetterCommerceOperation, getGatewayId, } = require("../../../../dist");

const config = { "id": 48, "systemName": "OmniCapital", "displayName": "OmniCapital", "slug": null, "isOnsite": false, "enabled": true, "isBillingAddressRequired": false, "displayOrder": 0, "iconCssClass": "Apps-omniCapital.png", "description": "Use the OmniCapital payment gateway", "enableImmediateCapture": false, "forSubscription": false, "inputType": 15, "notificationUrl": null, "settings": [{ "key": "AccountCode", "value": "4641" }, { "key": "Signature", "value": "518KkIqSzw+nXlalicf4S29/97Y" }, { "key": "MotoUserName", "value": "Sanjay_pc" }, { "key": "MotoPassword", "value": "OmniCapital*2025@" }, { "key": "MotoSignature", "value": null }, { "key": "MotoAccountCode", "value": null }, { "key": "TestUrl", "value": "https://omniporttest.ocrf.co.uk/OnlineFormIntegration/Index" }, { "key": "ProductionUrl", "value": "https://omniporttest.ocrf.co.uk/OnlineFormIntegration/Index" }, { "key": "CancelUrl", "value": null }, { "key": "Version", "value": null }, { "key": "UseSandbox", "value": "True" }, { "key": "EnablePayInInstallment", "value": "False" }, { "key": "InstallmentDisplayText", "value": null }, { "key": "AdditionalServiceCharge", "value": "0.0" }, { "key": "EnableSplitPayment", "value": "False" }, { "key": "PrepaidValueType", "value": "Price" }, { "key": "MinimumPrepaidValue", "value": "0.0" }, { "key": "EnableImmediateCapture", "value": "False" }], "basicSettings": [{ "key": "Version", "value": null }, { "key": "OrderTypes", "value": "[\"Standard\",\"\"]" }], "message": null }

BCEnvironment.init("f148f128-1c3d-47a0-a9e2-45506c080971", "f7M2iEM0BBokUtsUDuQ6Hz7nASHnsowojOadmDj1QFY=", config, "https://auth.bettercommerce.io", "https://api20.bettercommerce.io")
BCEnvironment.addExtras({ country: "GB", currency: "GBP", language: "en", })


const data = { "CreditRequestID": "98833", "Identification[RetailerUniqueRef]": "{\"orderId\":\"10821-4335550\",\"id\":\"94cc19b9-3098-f011-98e4-83b5a3a6331e\"}", "Status": "COMPLETE", "Finance[Code]": "ONIB12-14.90-5697", "Finance[Deposit]": "250.00", "Goods[0][Description]": "937961V(5)", "Goods[0][Price]": "700.00", "Consumer[Title]": "Mr", "Consumer[Forename]": "Test", "Consumer[Surname]": "Test", "Consumer[PhoneNumber]": "01777777777", "Consumer[MobileNumber]": "07777777777", "Consumer[EmailAddress]": "sanjay@bettercommerce.io", "Consumer[HouseNumber]": "", "Consumer[HouseName]": "Address 1", "Consumer[Flat]": "", "Consumer[Street]": "", "Consumer[Town]": "London", "Consumer[Postcode]": "W44HH", "api_key": "518KkIqSzw+nXlalicf4S29/97Y", "InstallationID": "4641", "BrokerReference": "", "LoanApplicationId": "8f83f3cd-592f-4ba0-b604-cafef7ff2f40", "Info": "N/A", "cookies": {}, "extras": { "clientId": "f148f128-1c3d-47a0-a9e2-45506c080971", "sharedSecret": "f7M2iEM0BBokUtsUDuQ6Hz7nASHnsowojOadmDj1QFY=", "config": { "id": 48, "systemName": "OmniCapital", "displayName": "OmniCapital", "slug": null, "isOnsite": false, "enabled": true, "isBillingAddressRequired": false, "displayOrder": 0, "iconCssClass": "Apps-omniCapital.png", "description": "Use the OmniCapital payment gateway", "enableImmediateCapture": false, "forSubscription": false, "inputType": 15, "notificationUrl": null, "settings": [{ "key": "AccountCode", "value": "4641" }, { "key": "Signature", "value": "518KkIqSzw+nXlalicf4S29/97Y" }, { "key": "MotoUserName", "value": "Sanjay_pc" }, { "key": "MotoPassword", "value": "OmniCapital*2025@" }, { "key": "MotoSignature", "value": null }, { "key": "MotoAccountCode", "value": null }, { "key": "TestUrl", "value": "https://omniporttest.ocrf.co.uk/OnlineFormIntegration/Index" }, { "key": "ProductionUrl", "value": "https://omniporttest.ocrf.co.uk/OnlineFormIntegration/Index" }, { "key": "CancelUrl", "value": null }, { "key": "Version", "value": null }, { "key": "UseSandbox", "value": "True" }, { "key": "EnablePayInInstallment", "value": "False" }, { "key": "InstallmentDisplayText", "value": null }, { "key": "AdditionalServiceCharge", "value": "0.0" }, { "key": "EnableSplitPayment", "value": "False" }, { "key": "PrepaidValueType", "value": "Price" }, { "key": "MinimumPrepaidValue", "value": "0.0" }, { "key": "EnableImmediateCapture", "value": "False" }], "basicSettings": [{ "key": "Version", "value": null }, { "key": "OrderTypes", "value": "[\"Standard\",\"\"]" }], "message": null }, "authUrl": "https://auth.bettercommerce.io", "baseUrl": "https://api20.bettercommerce.io" } }

new BetterCommerceOperation().processPaymentHook({
    paymentMethodTypeId: 15,
    paymentMethodType: "OmniCapital",
    data,
}).then(paymentResponseResult => {
    console.log(' --- paymentResponseResult ---', paymentResponseResult)
}).catch((error) => {
    console.log(' --- error --- ', error)
})